export const heroes = {
  antimage: { name: 'Antimage', id: 1 },
  axe: { name: 'Axe', id: 2 },
  bane: { name: 'Bane', id: 3 },
  bloodseeker: { name: 'Bloodseeker', id: 4 },
  crystal_maiden: { name: 'Crystal Maiden', id: 5 },
  drow_ranger: { name: 'Drow Ranger', id: 6 },
  earthshaker: { name: 'Earthshaker', id: 7 },
  juggernaut: { name: 'Juggernaut', id: 8 },
  mirana: { name: 'Mirana', id: 9 },
  nevermore: { name: 'Nevermore', id: 11 },
  morphling: { name: 'Morphling', id: 10 },
  phantom_lancer: { name: 'Phantom Lancer', id: 12 },
  puck: { name: 'Puck', id: 13 },
  pudge: { name: 'Pudge', id: 14 },
  razor: { name: 'Razor', id: 15 },
  sand_king: { name: 'Sand King', id: 16 },
  storm_spirit: { name: 'Storm Spirit', id: 17 },
  sven: { name: 'Sven', id: 18 },
  tiny: { name: 'Tiny', id: 19 },
  vengefulspirit: { name: 'Vengeful Spirit', id: 20 },
  windrunner: { name: 'Windrunner', id: 21 },
  zuus: { name: 'Zuus', id: 22 },
  kunkka: { name: 'Kunkka', id: 23 },
  lina: { name: 'Lina', id: 25 },
  lich: { name: 'Lich', id: 31 },
  lion: { name: 'Lion', id: 26 },
  shadow_shaman: { name: 'Shadow Shaman', id: 27 },
  slardar: { name: 'Slardar', id: 28 },
  tidehunter: { name: 'Tidehunter', id: 29 },
  witch_doctor: { name: 'Witch Doctor', id: 30 },
  riki: { name: 'Riki', id: 32 },
  enigma: { name: 'Enigma', id: 33 },
  tinker: { name: 'Tinker', id: 34 },
  sniper: { name: 'Sniper', id: 35 },
  necrolyte: { name: 'Necrolyte', id: 36 },
  warlock: { name: 'Warlock', id: 37 },
  beastmaster: { name: 'Beastmaster', id: 38 },
  queenofpain: { name: 'Queen of Pain', id: 39 },
  venomancer: { name: 'Venomancer', id: 40 },
  faceless_void: { name: 'Faceless Void', id: 41 },
  skeleton_king: { name: 'Skeleton King', id: 42 },
  death_prophet: { name: 'Death Prophet', id: 43 },
  phantom_assassin: { name: 'Phantom Assassin', id: 44 },
  pugna: { name: 'Pugna', id: 45 },
  templar_assassin: { name: 'Templar Assassin', id: 46 },
  viper: { name: 'Viper', id: 47 },
  luna: { name: 'Luna', id: 48 },
  dragon_knight: { name: 'Dragon Knight', id: 49 },
  dazzle: { name: 'Dazzle', id: 50 },
  rattletrap: { name: 'Rattletrap', id: 51 },
  leshrac: { name: 'Leshrac', id: 52 },
  furion: { name: 'Furion', id: 53 },
  life_stealer: { name: 'Life Stealer', id: 54 },
  dark_seer: { name: 'Dark Seer', id: 55 },
  clinkz: { name: 'Clinkz', id: 56 },
  omniknight: { name: 'Omniknight', id: 57 },
  enchantress: { name: 'Enchantress', id: 58 },
  huskar: { name: 'Huskar', id: 59 },
  night_stalker: { name: 'Night Stalker', id: 60 },
  broodmother: { name: 'Broodmother', id: 61 },
  bounty_hunter: { name: 'Bounty Hunter', id: 62 },
  weaver: { name: 'Weaver', id: 63 },
  jakiro: { name: 'Jakiro', id: 64 },
  batrider: { name: 'Batrider', id: 65 },
  chen: { name: 'Chen', id: 66 },
  spectre: { name: 'Spectre', id: 67 },
  doom_bringer: { name: 'Doom Bringer', id: 69 },
  ancient_apparition: { name: 'Ancient Apparition', id: 68 },
  ursa: { name: 'Ursa', id: 70 },
  spirit_breaker: { name: 'Spirit Breaker', id: 71 },
  gyrocopter: { name: 'Gyrocopter', id: 72 },
  alchemist: { name: 'Alchemist', id: 73 },
  invoker: { name: 'Invoker', id: 74 },
  silencer: { name: 'Silencer', id: 75 },
  obsidian_destroyer: { name: 'Obsidian Destroyer', id: 76 },
  lycan: { name: 'Lycan', id: 77 },
  brewmaster: { name: 'Brewmaster', id: 78 },
  shadow_demon: { name: 'Shadow Demon', id: 79 },
  lone_druid: { name: 'Lone Druid', id: 80 },
  chaos_knight: { name: 'Chaos Knight', id: 81 },
  meepo: { name: 'Meepo', id: 82 },
  treant: { name: 'Treant', id: 83 },
  ogre_magi: { name: 'Ogre Magi', id: 84 },
  undying: { name: 'Undying', id: 85 },
  rubick: { name: 'Rubick', id: 86 },
  disruptor: { name: 'Disruptor', id: 87 },
  nyx_assassin: { name: 'Nyx Assassin', id: 88 },
  naga_siren: { name: 'Naga Siren', id: 89 },
  keeper_of_the_light: { name: 'Keeper of the Light', id: 90 },
  wisp: { name: 'Wisp', id: 91 },
  visage: { name: 'Visage', id: 92 },
  slark: { name: 'Slark', id: 93 },
  medusa: { name: 'Medusa', id: 94 },
  troll_warlord: { name: 'Troll Warlord', id: 95 },
  centaur: { name: 'Centaur', id: 96 },
  magnataur: { name: 'Magnataur', id: 97 },
  shredder: { name: 'Shredder', id: 98 },
  bristleback: { name: 'Bristleback', id: 99 },
  tusk: { name: 'Tusk', id: 100 },
  skywrath_mage: { name: 'Skywrath Mage', id: 101 },
  abaddon: { name: 'Abaddon', id: 102 },
  elder_titan: { name: 'Elder Titan', id: 103 },
  legion_commander: { name: 'Legion Commander', id: 104 },
  ember_spirit: { name: 'Ember Spirit', id: 106 },
  earth_spirit: { name: 'Earth Spirit', id: 107 },
  terrorblade: { name: 'Terrorblade', id: 109 },
  phoenix: { name: 'Phoenix', id: 110 },
  oracle: { name: 'Oracle', id: 111 },
  techies: { name: 'Techies', id: 105 },
  winter_wyvern: { name: 'Winter Wyvern', id: 112 },
  arc_warden: { name: 'Arc Warden', id: 113 },
  abyssal_underlord: { name: 'Abyssal Underlord', id: 108 },
  monkey_king: { name: 'Monkey King', id: 114 },
  pangolier: { name: 'Pangolier', id: 120 },
  dark_willow: { name: 'Dark Willow', id: 119 },
  grimstroke: { name: 'Grimstroke', id: 121 },
  mars: { name: 'Mars', id: 129 },
  void_spirit: { name: 'Void Spirit', id: 126 },
  snapfire: { name: 'Snapfire', id: 128 },
  hoodwink: { name: 'Hoodwink', id: 123 },
  dawnbreaker: { name: 'Dawnbreaker', id: 135 },
  marci: { name: 'Marci', id: 136 },
  primal_beast: { name: 'Primal Beast', id: 137 },
  muerta: { name: 'Muerta', id: 138 },
  ringmaster: { name: 'Ringmaster', id: 131 },
  kez: { name: 'Kez', id: 145 },
};

export const strength = [
  heroes.alchemist,
  heroes.axe,
  heroes.bristleback,
  heroes.centaur,
  heroes.chaos_knight,
  heroes.dawnbreaker,
  heroes.doom_bringer,
  heroes.dragon_knight,
  heroes.earth_spirit,
  heroes.earthshaker,
  heroes.elder_titan,
  heroes.huskar,
  heroes.kunkka,
  heroes.legion_commander,
  heroes.life_stealer,
  heroes.mars,
  heroes.night_stalker,
  heroes.ogre_magi,
  heroes.omniknight,
  heroes.primal_beast,
  heroes.pudge,
  heroes.slardar,
  heroes.spirit_breaker,
  heroes.sven,
  heroes.tidehunter,
  heroes.shredder,
  heroes.tiny,
  heroes.treant,
  heroes.tusk,
  heroes.abyssal_underlord,
  heroes.undying,
  heroes.skeleton_king,
];

export const agility = [
  heroes.antimage,
  heroes.arc_warden,
  heroes.bloodseeker,
  heroes.bounty_hunter,
  heroes.clinkz,
  heroes.drow_ranger,
  heroes.ember_spirit,
  heroes.faceless_void,
  heroes.gyrocopter,
  heroes.hoodwink,
  heroes.juggernaut,
  heroes.kez,
  heroes.luna,
  heroes.medusa,
  heroes.meepo,
  heroes.monkey_king,
  heroes.morphling,
  heroes.naga_siren,
  heroes.phantom_assassin,
  heroes.phantom_lancer,
  heroes.razor,
  heroes.riki,
  heroes.nevermore,
  heroes.slark,
  heroes.sniper,
  heroes.spectre,
  heroes.templar_assassin,
  heroes.terrorblade,
  heroes.troll_warlord,
  heroes.ursa,
  heroes.viper,
  heroes.weaver,
];

export const intelligence = [
  heroes.ancient_apparition,
  heroes.crystal_maiden,
  heroes.death_prophet,
  heroes.disruptor,
  heroes.enchantress,
  heroes.grimstroke,
  heroes.jakiro,
  heroes.keeper_of_the_light,
  heroes.leshrac,
  heroes.lich,
  heroes.lina,
  heroes.lion,
  heroes.muerta,
  heroes.furion,
  heroes.necrolyte,
  heroes.oracle,
  heroes.obsidian_destroyer,
  heroes.puck,
  heroes.pugna,
  heroes.queenofpain,
  heroes.ringmaster,
  heroes.rubick,
  heroes.shadow_demon,
  heroes.shadow_shaman,
  heroes.silencer,
  heroes.skywrath_mage,
  heroes.storm_spirit,
  heroes.tinker,
  heroes.warlock,
  heroes.witch_doctor,
  heroes.zuus,
];

export const universal = [
  heroes.abaddon,
  heroes.bane,
  heroes.batrider,
  heroes.beastmaster,
  heroes.brewmaster,
  heroes.broodmother,
  heroes.chen,
  heroes.rattletrap,
  heroes.dark_seer,
  heroes.dark_willow,
  heroes.dazzle,
  heroes.enigma,
  heroes.invoker,
  heroes.wisp,
  heroes.lone_druid,
  heroes.lycan,
  heroes.magnataur,
  heroes.marci,
  heroes.mirana,
  heroes.nyx_assassin,
  heroes.pangolier,
  heroes.phoenix,
  heroes.sand_king,
  heroes.snapfire,
  heroes.techies,
  heroes.vengefulspirit,
  heroes.venomancer,
  heroes.visage,
  heroes.void_spirit,
  heroes.windrunner,
  heroes.winter_wyvern,
];
